export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';

export const TOGGLE_CLIPPED = "TOGGLE_CLIPPED";
export const TOOLBAR_LEFT_CLIPPED = "TOOLBAR_LEFT_CLIPPED";
export const TOGGLE_DRAWER_VISIBILITY = "TOGGLE_DRAWER_VISIBILITY";
export const TOGGLE_MINI_VARIANT = "TOGGLE_MINI_VARIANT";
export const TOGGLE_FIXED_FOOTER = "TOGGLE_FIXED_FOOTER";
export const SIDENAV_DRAWER_POSITION = "SIDENAV_DRAWER_POSITION";
export const TOGGLE_FIXED_TOOLBAR = "TOGGLE_FIXED_TOOLBAR";
export const TOGGLE_TOOLBAR = "TOGGLE_TOOLBAR";
export const TOGGLE_FOOTER = "TOGGLE_FOOTER";
export const TOGGLE_FOOTER_TYPE = "TOGGLE_FOOTER_TYPE";
export const NAV_DRAWER_ALPHA_MOD = "NAV_DRAWER_ALPHA_MOD";
export const TOGGLE_MINIVARIENT_MODE = "TOGGLE_MINIVARIENT_MODE";
export const SET_DRAWER_ALPHA_IMG = "SET_DRAWER_ALPHA_IMG";

export const NAVIGATION_DRAWER_SCHEME = "NAVIGATION_DRAWER_SCHEME";
export const NAVIGATION_TOOLBAR_SCHEME = "NAVIGATION_TOOLBAR_SCHEME";
export const FOOTER_SCHEME = "FOOTER_SCHEME";
export const APP_COLOR_SCHEME = "APP_COLOR_SCHEME";
export const NAV_DRAWER_VARIANT_MOD = "NAV_DRAWER_VARIANT_MOD";
export const SET_TRANSITION_REPORTS = "SET_TRANSITION_REPORTS";

export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const USER_FORGOT_PASSWORD = "USER_FORGOT_PASSWORD";
export const USER_UPDATE_PROFILE = "USER_UPDATE_PROFILE";

export const USER_GET_ALL_REGIONS = "USER_GET_ALL_REGIONS";
export const USER_ADD_NEW_REGION = "USER_ADD_NEW_REGION";
export const USER_GET_REGION_DETAIL = "USER_GET_REGION_DETAIL";
export const USER_DELETE_REGION = "USER_DELETE_REGION";
export const USER_UPDATE_REGION = "USER_UPDATE_REGION";

export const USER_GET_ALL_COMPANIES = "USER_GET_ALL_COMPANIES";
export const USER_GET_COMPANY_DETAIL = "USER_GET_COMPANY_DETAIL";
export const USER_ADD_NEW_COMPANY = "USER_ADD_NEW_COMPANY";
export const USER_DELETE_COMPANY = "USER_DELETE_COMPANY";
export const USER_UPDATE_COMPANY = "USER_UPDATE_COMPANY";
export const USER_ADD_NEW_ADVICE_CONFOIRMATION = "USER_ADD_NEW_ADVICE_CONFOIRMATION";

export const USER_GET_ALL_CONTACTS = "USER_GET_ALL_CONTACTS";
export const USER_GET_CONTACT_DETAIL = "USER_GET_CONTACT_DETAIL";
export const USER_ADD_NEW_CONTACT = "USER_ADD_NEW_CONTACT";
export const USER_DELETE_CONTACT = "USER_DELETE_CONTACT";
export const USER_UPDATE_CONTACT = "USER_UPDATE_CONTACT";

export const USER_GET_ALL_COMMODITIES = "USER_GET_ALL_COMMODITIES";
export const USER_NEW_COMMODITY = "USER_NEW_COMMODITIES";
export const ADMIN_PUBLISH_COMMODITY = "ADMIN_PUBLISH_COMMODITY";
export const ADMIN_UNPUBLISH_COMMODITY = "ADMIN_UNPUBLISH_COMMODITY";

// commodity part for clients
export const GET_ALL_COMMODITY_SELECTION = "GET_ALL_COMMODITY_SELECTION";
export const GET_ALL_COMMODITY_SELECTION_ERR = "GET_ALL_COMMODITY_SELECTION_ERR";

// deliverypoint for clients
export const GET_ALL_DELIVERYPOINT_SELECTION = "GET_ALL_DELIVERYPOINT_SELECTION";
export const GET_ALL_DELIVERYPOINT_SELECTION_ERR = "GET_ALL_DELIVERYPOINT_SELECTION_ERR";

// request a deliverypoint for clients
export const REQUEST_ONE_DELIVERYPOINT_SELECTION = "REQUEST_ONE_DELIVERYPOINT_SELECTION";
export const REQUEST_ONE_DELIVERYPOINT_SELECTION_ERR = "REQUEST_ONE_DELIVERYPOINT_SELECTION_ERR";

//Getting Groups For Clients
export const GET_ALL_GROUPS = "GET_ALL_GROUPS";
export const GET_ALL_GROUPS_ERR = "GET_ALL_GROUPS_ERR";

//Adding A Group On Counter Parties Screen
export const ADD_GROUP = "ADD_GROUP";
export const ADD_GROUP_ERR = "ADD_GROUP_ERR";

//Deleting A Group On Counter Parties Screen
export const DELETE_GROUP = "DELETE_GROUP";
export const DELETE_GROUP_ERR = "DELETE_GROUP_ERR";

// Getting Counter Parties For Clients
export const GET_ALL_COUNTER_PARTIES = "GET_ALL_COUNTER_PARTIES";
export const GET_ALL_COUNTER_PARTIES_ERR = "GET_ALL_COUNTER_PARTIES_ERR";

// Adding Counter Party
export const ADD_COUNTER_PARTY = "ADD_COUNTER_PARTY";
export const ADD_COUNTER_PARTY_ERR = "ADD_COUNTER_PARTY_ERR";

// Updating Counter Party
export const UPDATE_COUNTER_PARTY = "UPDATE_COUNTER_PARTY";
export const UPDATE_COUNTER_PARTY_ERR = "UPDATE_COUNTER_PARTY_ERR";

// commodity grades
export const USER_GET_ALL_COMMODITYGRADES = "USER_GET_ALL_COMMODITYGRADES";
export const ADMIN_ADD_NEW_COMMODITYGRADE = "ADMIN_ADD_NEW_COMMODITYGRADE";

// delivery periods
export const USER_GET_ALL_DELIVERYPERIODS = "USER_GET_ALL_DELIVERYPERIODS";

// delivery points
export const USER_GET_ALL_DELIVERYPOINTS = "USER_GET_ALL_DELIVERYPOINTS";

export const GET_ALL_ORDER = "GET_ALL_ORDER";
export const GET_TRADER_ALL_RECENT_ORDER = 'GET_TRADER_ALL_RECENT_ORDER';

// Farm Access Setting & Getting
export const SET_FARM_ACCESS = "SET_FARM_ACCESS";
export const GET_FARM_ACCESS_SETTING = "GET_FARM_ACCESS_SETTING";

export const CANCEL_TRADER_ALL_RECENT_ORDER = "CANCEL_TRADER_ALL_RECENT_ORDER";
export const CANCEL_TRADER_ONE_RECENT_ORDER = "CANCEL_TRADER_ONE_RECENT_ORDER";